#!/bin/sh

projectDir=$(git rev-parse --show-toplevel) #获取项目根目录
lintProjects=("app") #要检查的module
lintCommand="lintDebug"

for project in ${lintProjects[@]}
do
    # Android lint check
    echo "-----------------${project}项目开始lint检查-----------------"
    lintReportPath="${project}/build/reports/lint-results.html"
    issueCount=$(./gradlew :app:$lintCommand 2>&1 | grep -oE 'out of [0-9]+' | grep -oE '[0-9]+')

    if [[ $issueCount -ne 0 ]] #不等于0
    then
        echo "${project}项目有${issueCount}个错误待修复，错误修复完成后方可进行提交!!!"
        echo "具体信息可以看 ${projectDir}/${lintReportPath}"
        exit 1
    fi

    echo "${project}项目Lint检查没有发现错误"
    exit 0
done